//BLOCK

StartupEvents.registry("block", (event) => {

	event.create("dragon_block")
		.displayName("Dragon Caster")
		.hardness(2.0)
		.resistance(8.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.lightLevel(0.53)
		.property(BlockProperties.ENABLED)
		.requiresTool(true)
	
	event.create("amplifyer_totem")
		.displayName("Amplifyer Totem")
		.hardness(1.5)
		.resistance(6.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.lightLevel(0.26)
		.property(BlockProperties.ENABLED)
		.requiresTool(true)
	
	event.create("dark_stone")
		.displayName("Darkend Stone")
		.hardness(1.5)
		.resistance(6.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.requiresTool(true)
	
	event.create("dark_stone_slab","slab")
		.displayName("Darkend Stone Slab")
		.hardness(1.5)
		.resistance(6.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.requiresTool(true)
	
	event.create("mutation_catalyst")
		.displayName("Mutation Catalyst")
		.hardness(1.5)
		.resistance(6.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.renderType("cutout")
		.property(BlockProperties.LEVEL)
		.requiresTool(true)
	
	event.create("spark_catalyst")
		.displayName("Spark Catalyst")
		.hardness(1.5)
		.resistance(6.0)
		.soundType("stone")
		.mapColor("color_gray")
		.tagBlock("mineable/pickaxe")
		.renderType("cutout")
		.property(BlockProperties.LEVEL)
		.requiresTool(true)

	event.create("star_block")
		.displayName("Star Block")
		.hardness(5)
		.resistance(6.0)
		.soundType("metal")
		.mapColor("color_orange")
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_iron_tool")
		.requiresTool(true)

	event.create("unobtainium")
		.displayName("Unobtainium Block")
})
