
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 5

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 4
		#The amount of items transferred
		#Range: > 1
		basic = 8
		#The amount of items transferred
		#Range: > 1
		improved = 16
		#The amount of items transferred
		#Range: > 1
		advanced = 32
		#The amount of items transferred
		#Range: > 1
		ultimate = 64

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 50
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 200
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 400
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 800
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 1200

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 250
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 1000
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 4000
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 16000
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 24000

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 100
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 400
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 800
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 1600
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 24000

