StartupEvents.registry("block", event => {

	event.create("thermal:enderium_glass")
	.soundType("glass")
	.mapColor("color_cyan")
	.hardness(5.0)
	.resistance(1000.0)
	.lightLevel(global.calcLight(3))
	.defaultCutout()
	.renderType('cutout')
	.item(item => {
		item.rarity("uncommon")
	})

	event.create("thermal:signalum_glass")
	.soundType("glass")
	.mapColor("color_red")
	.hardness(5.0)
	.resistance(1000.0)
	.lightLevel(global.calcLight(7))
	.defaultCutout()
	.renderType('cutout')
	.item(item => {
		item.rarity("uncommon")
	})

	event.create("thermal:lumium_glass")
	.soundType("glass")
	.mapColor("color_yellow")
	.hardness(5.0)
	.resistance(1000.0)
	.lightLevel(global.calcLight(15))
	.defaultCutout()
	.renderType('cutout')
	.item(item => {
		item.rarity("uncommon")
	})

	event.create("thermal:obsidian_glass")
	.soundType("glass")
	.mapColor("podzol")
	.hardness(5.0)
	.resistance(1000.0)
	.defaultCutout()
	.renderType('cutout')
})